version: '3'
services:
  web:
    image: docker-node-express-mongoapp
    build: ./web-site
    #command: nodemon index.js
    command: nodemon app.js
    ports:
      - "3000:3000"
    volumes:
      - ./web-site:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    depends_on:
      - "mongo"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
       - "1234:1234"
